### ISSUE TITLE
video.js/dist/video-js.css:1:1: Unclosed block

### ISSUE THREAD

**Issue by razbakov** [windicss/windicss#255]
Importing css from `videojs` breaks build

### Steps to reproduce

```js
import videojs from "video.js";
import "video.js/dist/video-js.css";
```

### Actual result

```
ERROR  [vite:css] node_modules/video.js/dist/video-js.css:1:1: Unclosed block
  at Input.error (node_modules/vite/node_modules/postcss/lib/input.js:121:16)
  at Parser.unclosedBlock (node_modules/vite/node_modules/postcss/lib/parser.js:527:22)
  at Parser.endFile (node_modules/vite/node_modules/postcss/lib/parser.js:358:35)
  at Parser.parse (node_modules/vite/node_modules/postcss/lib/parser.js:63:10)
  at parse (node_modules/vite/node_modules/postcss/lib/parse.js:11:12)
  at new LazyResult (node_modules/vite/node_modules/postcss/lib/lazy-result.js:122:16)
  at Processor.process (node_modules/vite/node_modules/postcss/lib/processor.js:33:12)
  at compileCSS (node_modules/vite/dist/node/chunks/dep-66eb515d.js:18935:10)
  at async Object.transform (node_modules/vite/dist/node/chunks/dep-66eb515d.js:18567:50)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:18403:30)
  at async ModuleLoader.fetchModule (node_modules/rollup/dist/shared/rollup.js:18459:9)
  at async Promise.all (index 1)
  at async ModuleLoader.fetchStaticDependencies (node_modules/rollup/dist/shared/rollup.js:18485:34)
  at async Promise.all (index 0)
  at async ModuleLoader.fetchModule (node_modules/rollup/dist/shared/rollup.js:18461:9)
  at async node_modules/rollup/dist/shared/rollup.js:18434:48
```

**Comment by gunters63** [comment]
I think in this case it might be that the CSS parser stumbles on the base64 encoded font data.

The error points to this part of the CSS (I ran it through a beautifier):

````
@font-face {
	font-family: VideoJS;
	src: url(data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAABBIAAsAAAAAGoQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADsAAABUIIslek9TLzIAAAFEAAAAPgAAAFZRiV3RY21hcAAAAYQAAADQAAADIjn098ZnbHlmAAACVAAACv4AABEIAwnSw2hlYWQAAA1UAAAAKwAAADYSy2hLaGhlYQAADYAAAAAbAAAAJA4DB 

........ (and so on)

QAAAAA=) format("truetype");
	font-weight: 400;
	font-style: normal
}
````

The @font-face statement before was processed correctly.

**Comment by lincenying** [comment]
If you include `//` in the base64 code, there will be problems
