### ISSUE TITLE
Failed to load Windi on Vite - Svelte

### ISSUE THREAD

**Issue by chaosprint** [windicss/windicss#368]
### Reproduction
Just normal installation:
```
npm init @vitejs/app
npm i
npm i -D vite-plugin-windicss windicss
```
Then:
```JavaScript
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import WindiCSS from 'vite-plugin-windicss'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), WindiCSS()]
})
```
This step is optional for the error:
```JavaScript
// main.js
import 'virtual:windi.css'
```

Finally:
```
npm run dev
```

### Logs
```JavaScript
failed to load config from C:\Users\chaosprint\dev\glicol-live\vite.config.js
error when starting dev server:
TypeError: WindiCSS is not a function
    at file:///C:/Users/chaosprint/dev/glicol-live/vite.config.js?t=1624866014454:7:23
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async loadConfigFromFile (C:\Users\chaosprint\dev\glicol-live\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:71977:31)
    at async resolveConfig (C:\Users\chaosprint\dev\glicol-live\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:71600:28)     
    at async createServer (C:\Users\chaosprint\dev\glicol-live\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:70142:20)      
    at async CAC.<anonymous> (C:\Users\chaosprint\dev\glicol-live\node_modules\vite\dist\node\cli.js:13892:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chaosprint\AppData\Roaming\npm-cache\_logs\2021-06-28T07_40_14_695Z-debug.log
```

### System Info
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 10.31 GB / 15.93 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.59)
    Internet Explorer: 11.0.19041.1
```

**Comment by chaosprint** [comment]
fixed by removing `"type": "module"` in `package.json`

**Comment by dominikg** [comment]
you should be able to do this instead of removing type: module
```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import WindiCSS from 'vite-plugin-windicss'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), WindiCSS.default()]
})
```

**Comment by BunnyTheLifeguard** [comment]
> you should be able to do this instead of removing type: module
> 
> ```js
> import { defineConfig } from 'vite'
> import { svelte } from '@sveltejs/vite-plugin-svelte'
> import WindiCSS from 'vite-plugin-windicss'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [svelte(), WindiCSS.default()]
> })
> ```

![image](https://user-images.githubusercontent.com/36411819/145026087-9d386e00-2298-455a-a9d1-51980667b4c7.png)

Does not exist? 🤔
