### ISSUE TITLE
[webpack-cli] Promise rejection: TypeError: WindiCSS is not a constructor

### ISSUE THREAD

**Issue by lautiamkok** [windicss/windicss#370]
Following the installation guide here https://windicss.org/integrations/webpack.html for webpack, I get the following error:

```
[webpack-cli] Promise rejection: TypeError: WindiCSS is not a constructor
[webpack-cli] TypeError: WindiCSS is not a constructor
    at Object.<anonymous> (/home/webpack-5/webpack.common.js:237:5)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/webpack-5/webpack.development.js:2:16)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/webpack-5/webpack.config.js:1:89)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

Why?

I am using webpack 5.

**Comment by KiryaAfimin** [comment]
const WindiCSS = require('windicss-webpack-plugin').default;

**Comment by lautiamkok** [comment]
@KiryaAfimin thanks. I figured that out in the end. The documentation is extremely poor. Lots of issues with webpack and conflicting with other webpack plugins. I think it's a shame that I have to give this framework a miss and go back for Tailwind instead. Less buggy.
