### ISSUE TITLE
Expected an opening bracket

### ISSUE THREAD

**Issue by ArthurDanjou** [windicss/windicss#424]
Hello, I have an error while I build my Nuxt app. I use windiness version 3.1.7 with Nuxt-windicss version 1.2.3.

I have this error when I type `Nuxt build`:
```
ERROR in ./virtual:windi.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/windicss-webpack-plugin/dist/loaders/virtual-module.js!./virtual:windi.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Expected an opening square bracket.
    at /Users/arthurdanjou/Documents/Workspace/Ares/virtual:windi.css:456:1
    at Root._error (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:137:24)
    at Root.error (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/root.js:43:25)
    at Parser.error (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:392:25)
    at Parser.expected (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:685:25)
    at Parser.missingSquareBracket (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:406:21)
    at Parser.parse (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:668:22)
    at Parser.loop (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:618:18)
    at new Parser (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:129:14)
    at Processor._root (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.processSync (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at getParsed (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/dist/index.js:34:59)
    at /Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss-minify-selectors/dist/index.js:196:39
    at /Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss/lib/container.js:243:18
    at /Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss/lib/container.js:139:18
    at Root.each (/Users/arthurdanjou/Documents/Workspace/Ares/node_modules/postcss/lib/container.js:105:16)
 @ ./virtual:windi.css 4:14-233
 @ ./src/plugins/main.ts
 @ ./build/index.js
 @ ./build/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./build/composition-api/register.js ./build/client.js
 ```

**Comment by antfu** [comment]
Can't really help without a proper reproduction.

**Comment by ArthurDanjou** [comment]
Here is my repository https://github.com/ArthurDanjou/Ares/tree/dev

**Comment by ArthurDanjou** [comment]
Do tou know where the bug is from ? I need a solution to publish in production

**Comment by antfu** [comment]
Can you narrow down to a minimal reproduction? Thanks.

**Comment by ArthurDanjou** [comment]
When I reduce my project to https://github.com/ArthurDanjou/Ares/tree/bug_windicss, all is working

**Comment by ArthurDanjou** [comment]
I have located the problem, It is present in two components. When I delete the components, the problem disappear

**Comment by ArthurDanjou** [comment]
[AboutHome](https://github.com/ArthurDanjou/Ares/blob/dev/src/components/Announcement.vue) and [Announcement](https://github.com/ArthurDanjou/Ares/blob/dev/src/components/Announcement.vue)

**Comment by ArthurDanjou** [comment]
Even if the files are empty, the build crash, so I think the names are bug

**Comment by ArthurDanjou** [comment]
I fix the problem by adding a few configuration Nuxt side.

Here is the build configuration : 
```ts
postcss: {
    preset: {
      features: {
        "focus-within-pseudo-class": false
      }
    }
  }
  ```
