### ISSUE TITLE
[vue-windicss-preprocess] handler is not a function

### ISSUE THREAD

**Issue by regenrek** [windicss/windicss#44]
Hi

thanks for this great project!

I stumbled upon some issue on my project. I basically did the setup according to the docs.

https://github.com/regenrek/nuxt-storyblok-starter/blob/windicss/nuxt.config.js#L123
https://github.com/regenrek/nuxt-storyblok-starter/blob/windicss/package.json#L55
https://github.com/regenrek/nuxt-storyblok-starter/blob/windicss/tailwind.config.js

I installed the `vue-windicss-precocess` manually due npx raised an error according to #42

After starting the dev server I'm stuck at this error

```
 ERROR  in ./.nuxt/components/nuxt-error.vue                              friendly-errors 22:11:36

Module build failed (from ./node_modules/vue-windicss-preprocess/index.js):
TypeError: handler is not a function
    at Processor.loadPlugin (/Users/jondoe/projects/nuxt-storyblok-starter/node_modules/windicss/lib/index.js:15719:9)
    at /Users/jondoe/projects/nuxt-storyblok-starter/node_modules/windicss/lib/index.js:15477:166
    at Array.map (<anonymous>)
    at Processor.resolveConfig (/Users/jondoe/projects/nuxt-storyblok-starter/node_modules/windicss/lib/index.js:15477:77)
    at new Processor (/Users/jondoe/projects/nuxt-storyblok-starter/node_modules/windicss/lib/index.js:15386:29)
    at Object.index (/Users/jondoe/projects/nuxt-storyblok-starter/node_modules/vue-windicss-preprocess/index.js:308:21)
                                                                          friendly-errors 22:11:36
 @ ./.nuxt/index.js 19:0-52 518:0-32
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```
Thank you in advance
Regards !

**Comment by regenrek** [comment]
Ok it seems that my `aspect-ratio` plugin isn't compatible with windicss need to investigate.

https://github.com/regenrek/nuxt-storyblok-starter/blob/windicss/tailwind.config.js#L82
