### ISSUE TITLE
Started new nuxt project with Error: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by ManasMadrecha** [windicss/windicss#564]
Hi, I just installed a brand new nuxt project with `create-nuxt-app` and selected `windicss` while installing. Upon `npm run dev`, I got this error in terminal: 

```
TypeError: Right-hand side of 'instanceof' is not an object

        at node_modules\nuxt-windicss\dist\index.js:62319:40
at Array.find (<anonymous>)
at WebpackBundler.<anonymous> (node_modules\nuxt-windicss\dist\index.js:62319:26)
at WebpackBundler.<anonymous> (node_modules\@nuxt\kit\dist\index.js:812:17)
at WebpackClientConfig.extendConfig (node_modules\@nuxt\webpack\dist\webpack.js:1509:37)
at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:1544:50)
at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:1708:26)
at WebpackBundler.getWebpackConfig (node_modules\@nuxt\webpack\dist\webpack.js:2016:19)
at WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2023:12)
at Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:30)
at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:107:5)
at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by segidev** [comment]
Basically this piece of code:

```js
_kit.extendBuild.call(void 0, (config) => {
  const WindiCSSWebpackPlugin = __require("windicss-webpack-plugin").default;
  config.plugins = config.plugins || [];
  if (config.plugins.find((i) => i instanceof WindiCSSWebpackPlugin))
    return;
```

**Comment by segidev** [comment]
@ManasMadrecha 

The solution is to actually install the latest `nuxt-windicss`.

For me the `yarn create nuxt-app` installed version **1.1.1** of `nuxt-windicss`

Running `yarn add nuxt-windicss` installs version: **^2.0.12**

Now it starts normally
