### ISSUE TITLE
Failed to `transform` Tailwind plugins

### ISSUE THREAD

**Issue by kidonng** [windicss/windicss#570]
```sh
$ cd $(mktemp -d)
$ yarn add windicss @tailwindcss/ui
$ node -e "const { transform } = require('windicss/helpers');

internal/modules/cjs/loader.js:455
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './resolveConfig' is not defined by "exports" in /workspaces/test
/node_modules/windicss/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)                                                                      at Object.<anonymous> (/workspaces/test/node_modules/@tailwindcss/custom-forms/src/defaultOptions.js:1:22)              at Module._compile (internal/modules/cjs/loader.js:1072:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by Blakeinstein** [comment]
damn even i am facing the exact same issue

**Comment by ycjcl868** [comment]
same issue
