### ISSUE TITLE
svelte kit error

### ISSUE THREAD

**Issue by andronasef** [windicss/windicss#623]
when run the with sveltekit windicss daisyui - without diasy it works

```Shell
gitpod /workspace/template-sveltekit $ npm run dev

template-sveltekit@0.0.1 dev
svelte-kit dev

🌼 daisyUI components 1.19.0 https://github.com/saadeghi/daisyui

Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at String.indexOf ()
at guessClassName (file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:366:18)
at file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:367:67
at Array.map ()
at guessClassName (file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:367:41)
at file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:367:67
at Array.map ()
at guessClassName (file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:367:41)
at file:///workspace/template-sveltekit/node_modules/windicss/lib/index.mjs:367:67
at Array.map ()
file:///workspace/template-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:4410
throw new Error('Cannot close server before it is initialized');
^

Error: Cannot close server before it is initialized
at Watcher.close (file:///workspace/template-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:4410:10)
at process. (file:///workspace/template-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:4237:9)
at process.emit (node:events:390:28)
at process.emit (node:domain:475:12)
at process.exit (node:internal/process/per_thread:184:15)
at handle_error (file:///workspace/template-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:803:10)
at file:///workspace/template-sveltekit/node_modules/@sveltejs/kit/dist/cli.js:874:4
```

Windiconfig
```js
// @ts-check - enable TS check for js file
import { defineConfig ,transform } from 'windicss/helpers'

export default defineConfig({ plugins: [
transform('daisyui'),
],

/* configurations... */
})
```
svelte.config.js
```js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';
import WindiCSS from 'vite-plugin-windicss'

/** @type {import('@sveltejs/kit').Config} */
const config = {
// Consult https://github.com/sveltejs/svelte-preprocess
// for more information about preprocessors
preprocess: preprocess(),

kit: {
	adapter: adapter(),

	// hydrate the <div id="svelte"> element in src/app.html
	target: '#svelte',   vite: {
		     plugins: [
		       WindiCSS(),
		     ],
		   },
		
}
};

```
package.json
```json
export default config;

{
"name": "template-sveltekit",
"version": "0.0.1",
"scripts": {
"dev": "svelte-kit dev",
"build": "svelte-kit build",
"package": "svelte-kit package",
"preview": "svelte-kit preview",
"check": "svelte-check --tsconfig ./tsconfig.json",
"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
"lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
"format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
},
"devDependencies": {
"@sveltejs/adapter-auto": "next",
"@sveltejs/kit": "next",
"@typescript-eslint/eslint-plugin": "^4.31.1",
"@typescript-eslint/parser": "^4.31.1",
"eslint": "^7.32.0",
"eslint-config-prettier": "^8.3.0",
"eslint-plugin-svelte3": "^3.2.1",
"prettier": "^2.4.1",
"prettier-plugin-svelte": "^2.4.0",
"svelte": "^3.44.0",
"svelte-check": "^2.2.6",
"svelte-preprocess": "^4.9.4",
"tslib": "^2.3.1",
"typescript": "^4.4.3",
"vite-plugin-windicss": "^1.6.1"
},
"type": "module",
"dependencies": {
"daisyui": "^1.19.0"
}
}


```

**Comment by lunw1024** [comment]
I got similar RangeError at `String.trim` using vite, windicss, and daisyui

**Comment by othernotherone** [comment]
I am getting the same range error at `String.trim` using vite, windicss, and daisyui as well - all inside of SveltePress. I got it to work, temporarily at least, by downgrading daisyui with`pnpm install -D daisyui@1.16.2`. I am not seeing that same range error with v1.16.2, so I think this is really a daisyui issue.
