### ISSUE TITLE
svelte-windicss-preprocess regression in 4.2 (_a.classes.replaceAll is not a function)

### ISSUE THREAD

**Issue by abovethewater** [windicss/windicss#644]
Following the SvelteKit guide for windi on a new(ish) project results in the app failing to load / preprocessing fails.

```
_a.classes.replaceAll is not a function
    at Magician.processClassAttribute (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:16850:76)
    at Magician.extract (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:16835:10)
    at markup (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:17020:23)
    at process_markup (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:16754:27)
    at preprocess (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:16776:32)
    at markup (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte-windicss-preprocess@4.2.5/node_modules/svelte-windicss-preprocess/dist/index.mjs:17211:29)
    at async process_markup (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/compiler.mjs:31602:23)
    at async preprocess (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/svelte@3.44.3/node_modules/svelte/compiler.mjs:31632:30)
    at async compileSvelte2 (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.32_svelte@3.44.3+vite@2.7.7/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:297:20)
    at async handleHotUpdate (file:///Users/jmathews/abovethewater/last2versions.com/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.32_svelte@3.44.3+vite@2.7.7/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:182:23
```

The offending code is simply:

```
<div class="flex justify-center bg-blue-900"><h1>Test</h1></div>
```

Downgrading to `svelte-windicss-preprocess@4.1` seems to resolve the issue and windi is working.

```
pnpm install -D svelte-windicss-preprocess@4.1
Packages: +2 -7
++-------
Progress: resolved 233, reused 217, downloaded 0, added 0, done

devDependencies:
- svelte-windicss-preprocess 4.2.5
+ svelte-windicss-preprocess 4.1.7 (4.2.5 is available)
```

No `windi.config.js`

svelte.config.js:

```
import adapter from '@sveltejs/adapter-static'
import preprocess from 'svelte-preprocess'
import { windi } from 'svelte-windicss-preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: [preprocess(), windi({})],

  kit: {
    adapter: adapter(),

    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte'
  }
}

export default config
```

**Comment by silasabbott** [comment]
I just ran into this issue after upgrading to 4.2

You will need to use Node v16. In VSCode, point the `svelte.language-server.runtime` option in your `settings.json` to Node v16 on your machine. If you're using `nvm`, set your `.nvmrc` to 16 or run `nvm use 16` before you start the development server

**Comment by deklanw** [comment]
Confirming that upgrading my Node from 14 to 17 and setting `svelte.language-server.runtime` fixed it.

**Comment by alexanderniebuhr** [comment]
Should be fixed.
