### ISSUE TITLE
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by seanaye** [windicss/windicss#799]
package: `rollup-plugin-windicss: 1.8.4`

When compiling with `rollup -c` I get the following error.

```
/Users/seanaye/dev/personal/portfolio/packages/ui/src/index.tsx → dist/browser/index.module.js...
@seanaye/ui:build: [!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
@seanaye/ui:build: ../../../../../../../@windicss/windi.css (1:0)
@seanaye/ui:build: 1: /* windicss layer base */
@seanaye/ui:build:    ^
@seanaye/ui:build: 2: *, ::before, ::after {
@seanaye/ui:build: 3:   -webkit-box-sizing: border-box;
@seanaye/ui:build: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
@seanaye/ui:build:     at error (/Users/seanaye/dev/personal/portfolio/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:198:30)
@seanaye/ui:build:     at Module.error (/Users/seanaye/dev/personal/portfolio/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:12553:16)
@seanaye/ui:build:     at Module.tryParse (/Users/seanaye/dev/personal/portfolio/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:12930:25)
@seanaye/ui:build:     at Module.setSource (/Users/seanaye/dev/personal/portfolio/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:12835:24)
@seanaye/ui:build:     at ModuleLoader.addModuleSource (/Users/seanaye/dev/personal/portfolio/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22309:20)
@seanaye/ui:build: 
@seanaye/ui:build:  ELIFECYCLE  Command failed with exit code 1.
@seanaye/ui:build: ERROR: command finished with error: command (packages/ui) pnpm run build exited (1)
```

my rollup.config.js

```js
import withSolid from "rollup-preset-solid";
import WindiCSS from "rollup-plugin-windicss";

export default withSolid([
  { input: "src/index.tsx", mappingName: "browser", plugins: [...WindiCSS()] },
  {
    input: "src/index.tsx",
    mappingName: "server",
    solidOptions: { generate: "ssr", hydratable: true },
    plugins: [...WindiCSS()],
  },
]);
```

**Comment by rookiePrgrmer** [comment]
same problem! have u solved it?
