### ISSUE TITLE
Couldn't start with Nuxt 3 stable version

### ISSUE THREAD

**Issue by parsagholipour** [windicss/windicss#878]
It seems nuxt 3.0.0 is not supported.
After upgrading nuxt to `^3.0.0` it gives this error at the build time.

`npm.cmd" run dev `
`Nuxt 3.0.0 with Nitro 1.0.0`

  `ERROR  Cannot start nuxt:  nuxt.options.buildModules is not iterable
  at setup (/node_modules/.pnpm/nuxt-windicss@2.5.2/node_modules/nuxt-windicss/dist/module.mjs:89:23)
  at normalizedModule (/node_modules/.pnpm/@nuxt+kit@3.0.0-rc.9/node_modules/@nuxt/kit/dist/index.mjs:630:29)
  at async installModule (/node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/node_modules/.pnpm/nuxt@3.0.0_7ilbxdl5iguzcjriqqcg2m5cku/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/cli.mjs:50:20)`

**Comment by parsagholipour** [comment]
Just had to upgrade windicss to the latest version
